In [1]:
import numpy as np
import pandas as pd
from pathlib import Path

In [2]:
# Read the CSV file  into a Pandas DataFrame
file_path = Path("C:/Users/jordo/OneDrive/Desktop/git-projects/Project-4/Resources/California/California_new_cancer.csv")
file_path2 = Path("C:/Users/jordo/OneDrive/Desktop/git-projects/Project-4/Resources/California/California_cancer_death.csv")
file_path3 = Path("C:/Users/jordo/OneDrive/Desktop/git-projects/Project-4/Resources/Florida/Florida_new_cancer.csv")
file_path4 = Path("C:/Users/jordo/OneDrive/Desktop/git-projects/Project-4/Resources/Florida/Florida_cancer_death.csv")
file_path5 = Path("C:/Users/jordo/OneDrive/Desktop/git-projects/Project-4/Resources/Texas/Texas_new_cancer.csv")
file_path6 = Path("C:/Users/jordo/OneDrive/Desktop/git-projects/Project-4/Resources/Texas/Texas_cancer_death.csv")

Cali_new_df = pd.read_csv(file_path)
Cali_death_df = pd.read_csv(file_path2)

Florida_new_df = pd.read_csv(file_path3)
Florida_death_df = pd.read_csv(file_path4)

Texas_new_df = pd.read_csv(file_path5)
Texas_death_df = pd.read_csv(file_path6)

# Review new cancer DataFrame
Cali_new_df.head()

,Area,County,Cancer Type,Year,Sex,Age-Adjusted Rate,Case Count,Population
0,California,Alpine County,All Types of Cancer,2016-2020,Male and Female,271.7,22,5482
1,California,Sierra County,All Types of Cancer,2016-2020,Male and Female,307.7,88,14804
2,California,Modoc County,All Types of Cancer,2016-2020,Male and Female,310.5,220,44266
3,California,Mono County,All Types of Cancer,2016-2020,Male and Female,250.9,235,71973
4,California,Trinity County,All Types of Cancer,2016-2020,Male and Female,378.7,426,62705

In [3]:
# Review Death DataFrame
Cali_death_df.head()

,Area,County,Cancer Type,Year,Sex,Age-Adjusted Rate,Death Count,Population
0,California,Alpine County,All Types of Cancer,2016-2020,Male and Female,235.3,19,5482
1,California,Sierra County,All Types of Cancer,2016-2020,Male and Female,98.1,31,14804
2,California,Mono County,All Types of Cancer,2016-2020,Male and Female,57.1,55,71973
3,California,Modoc County,All Types of Cancer,2016-2020,Male and Female,121.6,99,44266
4,California,Trinity County,All Types of Cancer,2016-2020,Male and Female,116.3,142,62705

In [4]:
Cali_new_df = Cali_new_df.rename(columns={"Age-Adjusted Rate":"New Case Rate"})
Cali_death_df = Cali_death_df.rename(columns={"Age-Adjusted Rate":"Death Rate"})

Cali_new_df.head()

,Area,County,Cancer Type,Year,Sex,New Case Rate,Case Count,Population
0,California,Alpine County,All Types of Cancer,2016-2020,Male and Female,271.7,22,5482
1,California,Sierra County,All Types of Cancer,2016-2020,Male and Female,307.7,88,14804
2,California,Modoc County,All Types of Cancer,2016-2020,Male and Female,310.5,220,44266
3,California,Mono County,All Types of Cancer,2016-2020,Male and Female,250.9,235,71973
4,California,Trinity County,All Types of Cancer,2016-2020,Male and Female,378.7,426,62705

In [5]:
Cali_death_df.head()

,Area,County,Cancer Type,Year,Sex,Death Rate,Death Count,Population
0,California,Alpine County,All Types of Cancer,2016-2020,Male and Female,235.3,19,5482
1,California,Sierra County,All Types of Cancer,2016-2020,Male and Female,98.1,31,14804
2,California,Mono County,All Types of Cancer,2016-2020,Male and Female,57.1,55,71973
3,California,Modoc County,All Types of Cancer,2016-2020,Male and Female,121.6,99,44266
4,California,Trinity County,All Types of Cancer,2016-2020,Male and Female,116.3,142,62705

In [6]:
Florida_new_df = Florida_new_df.rename(columns={"Age-Adjusted Rate":"New Case Rate"})
Florida_death_df = Florida_death_df.rename(columns={"Age-Adjusted Rate":"Death Rate"})

Florida_new_df.head()

,Area,County,Cancer Type,Year,Sex,New Case Rate,Case Count,Population
0,Florida,Liberty County,All Types of Cancer,2016-2020,Male and Female,451.6,222,41667
1,Florida,Lafayette County,All Types of Cancer,2016-2020,Male and Female,452.0,232,42878
2,Florida,Holmes County,All Types of Cancer,2016-2020,Male and Female,267.2,365,97651
3,Florida,Hamilton County,All Types of Cancer,2016-2020,Male and Female,405.9,382,71986
4,Florida,Franklin County,All Types of Cancer,2016-2020,Male and Female,430.6,409,59572

In [7]:
Florida_death_df.head()

,Area,County,Cancer Type,Year,Sex,Death Rate,Death Count,Population
0,Florida,Liberty County,All Types of Cancer,2016-2020,Male and Female,179.7,86,41667
1,Florida,Lafayette County,All Types of Cancer,2016-2020,Male and Female,193.8,100,42878
2,Florida,Glades County,All Types of Cancer,2016-2020,Male and Female,124.3,159,68886
3,Florida,Franklin County,All Types of Cancer,2016-2020,Male and Female,172.6,170,59572
4,Florida,Jefferson County,All Types of Cancer,2016-2020,Male and Female,161.4,189,71392

In [8]:
Texas_new_df = Texas_new_df.rename(columns={"Age-Adjusted Rate":"New Case Rate"})
Texas_death_df = Texas_death_df.rename(columns={"Age-Adjusted Rate":"Death Rate"})

Texas_new_df.head()

,Area,County,Cancer Type,Year,Sex,New Case Rate,Case Count,Population
0,Texas,Kenedy County,All Types of Cancer,2016-2020,Male and Female,Data not presented,Data not presented,Data not presented
1,Texas,King County,All Types of Cancer,2016-2020,Male and Female,Data not presented,Data not presented,Data not presented
2,Texas,Loving County,All Types of Cancer,2016-2020,Male and Female,Data not presented,Data not presented,Data not presented
3,Texas,Terrell County,All Types of Cancer,2016-2020,Male and Female,329.6,18,3871
4,Texas,Roberts County,All Types of Cancer,2016-2020,Male and Female,306.1,21,4386

In [9]:
Texas_death_df.head()

,Area,County,Cancer Type,Year,Sex,Death Rate,Death Count,Population
0,Texas,Terrell County,All Types of Cancer,2016-2020,Male and Female,Data not presented,Data not presented,Data not presented
1,Texas,Roberts County,All Types of Cancer,2016-2020,Male and Female,Data not presented,Data not presented,Data not presented
2,Texas,Sterling County,All Types of Cancer,2016-2020,Male and Female,Data not presented,Data not presented,Data not presented
3,Texas,McMullen County,All Types of Cancer,2016-2020,Male and Female,Data not presented,Data not presented,Data not presented
4,Texas,Loving County,All Types of Cancer,2016-2020,Male and Female,Data not presented,Data not presented,Data not presented

In [10]:
Cali_cancer_df = pd.merge(Cali_new_df, Cali_death_df, how="left", on=["County", "County"])
Cali_cancer_df.head()

,Area_x,County,Cancer Type_x,Year_x,Sex_x,New Case Rate,Case Count,Population_x,Area_y,Cancer Type_y,Year_y,Sex_y,Death Rate,Death Count,Population_y
0,California,Alpine County,All Types of Cancer,2016-2020,Male and Female,271.7,22,5482,California,All Types of Cancer,2016-2020,Male and Female,235.3,19,5482
1,California,Sierra County,All Types of Cancer,2016-2020,Male and Female,307.7,88,14804,California,All Types of Cancer,2016-2020,Male and Female,98.1,31,14804
2,California,Modoc County,All Types of Cancer,2016-2020,Male and Female,310.5,220,44266,California,All Types of Cancer,2016-2020,Male and Female,121.6,99,44266
3,California,Mono County,All Types of Cancer,2016-2020,Male and Female,250.9,235,71973,California,All Types of Cancer,2016-2020,Male and Female,57.1,55,71973
4,California,Trinity County,All Types of Cancer,2016-2020,Male and Female,378.7,426,62705,California,All Types of Cancer,2016-2020,Male and Female,116.3,142,62705

In [11]:
Cali_cancer_df = Cali_cancer_df[["Area_x", "County", "New Case Rate", "Case Count", "Population_x", "Death Rate", "Death Count"]]
Cali_cancer_df = Cali_cancer_df.rename(columns={"Area_x":"Area", "Population_x": "Population"})
Cali_cancer_df.head()

,Area,County,New Case Rate,Case Count,Population,Death Rate,Death Count
0,California,Alpine County,271.7,22,5482,235.3,19
1,California,Sierra County,307.7,88,14804,98.1,31
2,California,Modoc County,310.5,220,44266,121.6,99
3,California,Mono County,250.9,235,71973,57.1,55
4,California,Trinity County,378.7,426,62705,116.3,142

In [12]:
Cali_cancer_df.to_csv('California_cancer', encoding='utf-8')

In [13]:
Florida_cancer_df = pd.merge(Florida_new_df, Florida_death_df, how="left", on=["County", "County"])
Florida_cancer_df.head()

,Area_x,County,Cancer Type_x,Year_x,Sex_x,New Case Rate,Case Count,Population_x,Area_y,Cancer Type_y,Year_y,Sex_y,Death Rate,Death Count,Population_y
0,Florida,Liberty County,All Types of Cancer,2016-2020,Male and Female,451.6,222,41667,Florida,All Types of Cancer,2016-2020,Male and Female,179.7,86,41667
1,Florida,Lafayette County,All Types of Cancer,2016-2020,Male and Female,452.0,232,42878,Florida,All Types of Cancer,2016-2020,Male and Female,193.8,100,42878
2,Florida,Holmes County,All Types of Cancer,2016-2020,Male and Female,267.2,365,97651,Florida,All Types of Cancer,2016-2020,Male and Female,175.9,254,97651
3,Florida,Hamilton County,All Types of Cancer,2016-2020,Male and Female,405.9,382,71986,Florida,All Types of Cancer,2016-2020,Male and Female,202.9,191,71986
4,Florida,Franklin County,All Types of Cancer,2016-2020,Male and Female,430.6,409,59572,Florida,All Types of Cancer,2016-2020,Male and Female,172.6,170,59572

In [14]:
Florida_cancer_df = Florida_cancer_df[["Area_x", "County", "New Case Rate", "Case Count", "Population_x", "Death Rate", "Death Count"]]
Florida_cancer_df = Florida_cancer_df.rename(columns={"Area_x":"Area", "Population_x": "Population"})
Florida_cancer_df.head()

,Area,County,New Case Rate,Case Count,Population,Death Rate,Death Count
0,Florida,Liberty County,451.6,222,41667,179.7,86
1,Florida,Lafayette County,452.0,232,42878,193.8,100
2,Florida,Holmes County,267.2,365,97651,175.9,254
3,Florida,Hamilton County,405.9,382,71986,202.9,191
4,Florida,Franklin County,430.6,409,59572,172.6,170

In [15]:
Florida_cancer_df.to_csv('Florida_cancer', encoding='utf-8')

In [16]:
Texas_cancer_df = pd.merge(Texas_new_df, Texas_death_df, how="left", on=["County", "County"])
Texas_cancer_df.head()

,Area_x,County,Cancer Type_x,Year_x,Sex_x,New Case Rate,Case Count,Population_x,Area_y,Cancer Type_y,Year_y,Sex_y,Death Rate,Death Count,Population_y
0,Texas,Kenedy County,All Types of Cancer,2016-2020,Male and Female,Data not presented,Data not presented,Data not presented,Texas,All Types of Cancer,2016-2020,Male and Female,Data not presented,Data not presented,Data not presented
1,Texas,King County,All Types of Cancer,2016-2020,Male and Female,Data not presented,Data not presented,Data not presented,Texas,All Types of Cancer,2016-2020,Male and Female,Data not presented,Data not presented,Data not presented
2,Texas,Loving County,All Types of Cancer,2016-2020,Male and Female,Data not presented,Data not presented,Data not presented,Texas,All Types of Cancer,2016-2020,Male and Female,Data not presented,Data not presented,Data not presented
3,Texas,Terrell County,All Types of Cancer,2016-2020,Male and Female,329.6,18,3871,Texas,All Types of Cancer,2016-2020,Male and Female,Data not presented,Data not presented,Data not presented
4,Texas,Roberts County,All Types of Cancer,2016-2020,Male and Female,306.1,21,4386,Texas,All Types of Cancer,2016-2020,Male and Female,Data not presented,Data not presented,Data not presented

In [17]:
Texas_cancer_df = Texas_cancer_df[["Area_x", "County", "New Case Rate", "Case Count", "Population_x", "Death Rate", "Death Count"]]
Texas_cancer_df = Texas_cancer_df.rename(columns={"Area_x":"Area", "Population_x": "Population"})
Texas_cancer_df.head()

,Area,County,New Case Rate,Case Count,Population,Death Rate,Death Count
0,Texas,Kenedy County,Data not presented,Data not presented,Data not presented,Data not presented,Data not presented
1,Texas,King County,Data not presented,Data not presented,Data not presented,Data not presented,Data not presented
2,Texas,Loving County,Data not presented,Data not presented,Data not presented,Data not presented,Data not presented
3,Texas,Terrell County,329.6,18,3871,Data not presented,Data not presented
4,Texas,Roberts County,306.1,21,4386,Data not presented,Data not presented

In [ ]:
Florida_cancer_df.to_csv('Florida_cancer', encoding='utf-8')