In [7]:
#Imports
import numpy as np
import pandas as pd
from pathlib import Path

In [8]:
# Import all state dfs
Alaska_df = pd.read_csv(
    "Alaska/Alaska Complete.csv")

Vermont_df = pd.read_csv(
    "Vermont/Vermont_Complete.csv")

Wyoming_df = pd.read_csv(
    "Wyoming/Wyoming_Complete.csv")

California_df = pd.read_csv(
    "California/California_Complete.csv")

Florida_df = pd.read_csv(
    "Florida/Florida_Complete.csv")
Texas_df = pd.read_csv(
    "Texas/Texas_Complete.csv")

#View dfs
Florida_df.head()

,Unnamed: 0,County,FIPS,Income,Uninsured %,White Poverty %,Black Poverty %,Asian Poverty %,Foreign Poverty %,Native Poverty %,Hispanic Poverty %,County FIPS,Non Hispanic Poverty %,Area,New Case Rate,Case Count,Population,Death Rate,Death Count
0,0,St. Johns,12109.0,88794.0,4.7,84.9,5.3,3.1,8.0,0.1,7.6,12109.0,92.4,Florida,488.8,8839.0,1277049.0,132.8,2464.0
1,1,Nassau,12089.0,77504.0,4.8,88.5,5.5,1.0,4.0,0.3,4.8,12089.0,95.2,Florida,555.9,3624.0,428811.0,176.4,1167.0
2,2,Santa Rosa,12113.0,77260.0,4.9,83.7,5.9,2.1,5.0,0.4,6.0,12113.0,94.0,Florida,481.4,5343.0,897936.0,152.7,1675.0
3,3,Collier,12021.0,75543.0,4.2,79.6,6.6,1.5,25.6,0.2,28.5,12021.0,71.5,Florida,402.0,14261.0,1896727.0,102.6,4288.0
4,4,Clay,12019.0,74059.0,4.8,75.2,11.0,2.9,6.4,0.1,10.5,12019.0,89.5,Florida,495.0,6446.0,1076468.0,166.3,2088.0

In [9]:
#Append state dfs together and display new dataframe
state_info_df =  pd.DataFrame().append([Alaska_df,Vermont_df,Wyoming_df,Florida_df,California_df,Texas_df])
state_info_df.head()

C:\Users\sholl\AppData\Local\Temp\ipykernel_24288\3037134974.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  state_info_df =  pd.DataFrame().append([Alaska_df,Vermont_df,Wyoming_df,Florida_df,California_df,Texas_df])

,Unnamed: 0,County,FIPS,Income,Uninsured %,White Poverty %,Black Poverty %,Asian Poverty %,Foreign Poverty %,Native Poverty %,...,Area,Age-Adjusted New Case Rate,Case Count,Population,Age-Adjusted Death Rate,Death Count,Uninsured,County FIPS,New Case Rate,Death Rate
0,13,Aleutians East,2013.0,72258,4.5,14.6,2.1,21.2,24.7,44.1,...,Alaska,138.9,23,16946,Data not presented,Data not presented,NaN,NaN,NaN,NaN
1,0,Aleutians West,2016.0,90708,3.8,24.5,3.5,47.5,45.3,10.5,...,Alaska,286.2,51,28538,114.2,19,NaN,NaN,NaN,NaN
2,2,Anchorage,2020.0,88871,5.4,60.3,5.4,12.6,11.0,7.2,...,Alaska,444,6278,1460452,146.1,1878,NaN,NaN,NaN,NaN
3,22,Bethel,2050.0,57460,18.1,9.6,0.9,1.6,2.3,84.5,...,Alaska,367.5,242,91317,195,104,NaN,NaN,NaN,NaN
4,7,Bristol Bay,2060.0,81563,2.4,44.8,0.6,5.7,7.9,33.2,...,Alaska,337.2,19,4284,Data not presented,Data not presented,NaN,NaN,NaN,NaN

In [10]:
#View dataframe end due to size
state_info_df.tail()

,Unnamed: 0,County,FIPS,Income,Uninsured %,White Poverty %,Black Poverty %,Asian Poverty %,Foreign Poverty %,Native Poverty %,...,Area,Age-Adjusted New Case Rate,Case Count,Population,Age-Adjusted Death Rate,Death Count,Uninsured,County FIPS,New Case Rate,Death Rate
250,250,Brooks,48047.0,26827,1.7,68.5,1.8,0.1,10.6,no data/suppressed,...,Texas,NaN,150,35499,NaN,70,NaN,48047.0,355.3,150.7
251,251,Presidio,48377.0,26395,7.8,69.6,no data/suppressed,1.4,43.0,1.9,...,Texas,NaN,124,34041,NaN,40,NaN,48377.0,262.2,74.7
252,252,Dimmit,48127.0,25000,5.9,60.4,0.2,1.6,10.2,0.2,...,Texas,NaN,198,51162,NaN,78,NaN,48127.0,348.8,128.9
253,253,Loving,48301.0,no data/suppressed,no data/suppressed,98.8,no data/suppressed,1.2,1.2,no data/suppressed,...,Texas,NaN,Data not presented,Data not presented,NaN,Data not presented,NaN,48301.0,Data not presented,Data not presented
254,254,undefined,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
#Remove unneeded columns
state_info_df = state_info_df.drop(columns="Unnamed: 0")
state_info_df.tail()

,County,FIPS,Income,Uninsured %,White Poverty %,Black Poverty %,Asian Poverty %,Foreign Poverty %,Native Poverty %,Hispanic Poverty %,...,Area,Age-Adjusted New Case Rate,Case Count,Population,Age-Adjusted Death Rate,Death Count,Uninsured,County FIPS,New Case Rate,Death Rate
250,Brooks,48047.0,26827,1.7,68.5,1.8,0.1,10.6,no data/suppressed,91.6,...,Texas,NaN,150,35499,NaN,70,NaN,48047.0,355.3,150.7
251,Presidio,48377.0,26395,7.8,69.6,no data/suppressed,1.4,43.0,1.9,80.0,...,Texas,NaN,124,34041,NaN,40,NaN,48377.0,262.2,74.7
252,Dimmit,48127.0,25000,5.9,60.4,0.2,1.6,10.2,0.2,87.8,...,Texas,NaN,198,51162,NaN,78,NaN,48127.0,348.8,128.9
253,Loving,48301.0,no data/suppressed,no data/suppressed,98.8,no data/suppressed,1.2,1.2,no data/suppressed,no data/suppressed,...,Texas,NaN,Data not presented,Data not presented,NaN,Data not presented,NaN,48301.0,Data not presented,Data not presented
254,undefined,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
#Export state info df to csv
state_info_df.to_csv('State_Complete_Info.csv', encoding='utf-8')